server:
  port: 8862

spring:
  application:
    name: msvc-reservation

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ReservationDB?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: admin123

  jpa:
    hibernate:
      ddl-auto: create   # o update según tu necesidad
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

