server:
  port: 8100

spring:
  application:
    name: msvc-field

  data:
    mongodb:
      uri: mongodb://root:mongopass@localhost:27017/mydb?authSource=admin

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: grupo-canchas
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

